### ISSUE TITLE
ICASSP2023: Pushing the limits of self-supervised speaker verification using regularized distillation framework

### ISSUE THREAD

**Issue by yfchenlucky** [DmitryRyumin/ICASSP-2023-Papers#5]
Hello, thank you for your contributions.
Pushing the limits of self-supervised speaker verification using regularized distillation framework: https://github.com/alibaba-damo-academy/3D-Speaker

**Comment by DmitryRyumin** [comment]
> Hello, thank you for your contributions. Pushing the limits of self-supervised speaker verification using regularized distillation framework: https://github.com/alibaba-damo-academy/3D-Speaker

Hi @yfchenlucky, 👋

Thank you for the information! The article and all related content have been added to the following section: [Speaker Recognition: Verification, Diarization, Anti-Spoofing](https://github.com/DmitryRyumin/ICASSP-2023-Papers#speaker-recognition-verification-diarization-anti-spoofing).

P.S.: Currently, my priority for adding conferences is as follows: ICCV, ICASSP, CVPR.
