### ISSUE TITLE
Paper ID 2133

### ISSUE THREAD

**Issue by xuhangc** [DmitryRyumin/ICASSP-2023-Papers#6]
[ShaDocNet: Learning Spatial-Aware Tokens in Transformer for Document Shadow Removal](https://arxiv.org/abs/2211.16675)

Repo: https://github.com/CXH-Research/ShadocNet

Page: https://cxh-research.github.io/ShadocNet/

**Comment by DmitryRyumin** [comment]
Hi @xuhangc, 👋

Thanks for sharing this information.

I've added the article and all relevant details. If you have any changes in mind, please feel free to submit them via a pull request, as outlined in the [contributions section](https://github.com/DmitryRyumin/ICASSP-2023-Papers#contributors) of the GitHub repository.
